# Generated by Django 3.2.4 on 2021-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictclass',
            name='frase2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dictclass',
            name='frase3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dictclass',
            name='frasetrad2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dictclass',
            name='frasetrad3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frase',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frasetrad',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
