# Generated by Django 3.2.4 on 2021-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_auto_20210627_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictclass',
            name='Ordem',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frase',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frase2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frase3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frasetrad',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frasetrad2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='frasetrad3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='palavra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dictclass',
            name='palavratrad',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
