# Generated by Django 3.2.4 on 2021-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0003_auto_20210628_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictclass',
            name='SuaResposta1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dictclass',
            name='SuaResposta2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dictclass',
            name='SuaResposta3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
