# Generated by Django 3.2.4 on 2021-07-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0005_auto_20210629_1353'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dictclass',
            managers=[
            ],
        ),
    ]
