# Generated by Django 3.2.4 on 2021-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0006_alter_dictclass_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dictclass',
        ),
    ]
