# Generated by Django 3.2.4 on 2021-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictapp', '0007_delete_dictclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictclass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('palavra', models.CharField(blank=True, default='', max_length=255)),
                ('palavratrad', models.CharField(blank=True, default='', max_length=1000)),
                ('frase', models.CharField(blank=True, default='', max_length=1000)),
                ('frasetrad', models.CharField(blank=True, default='', max_length=1000)),
                ('frase2', models.CharField(blank=True, default='', max_length=1000)),
                ('frasetrad2', models.CharField(blank=True, default='', max_length=1000)),
                ('frase3', models.CharField(blank=True, default='', max_length=1000)),
                ('frasetrad3', models.CharField(blank=True, default='', max_length=1000)),
                ('figura1', models.CharField(max_length=1000)),
                ('som1', models.CharField(max_length=1000)),
                ('suaresposta1', models.TextField(blank=True, default='', max_length=1000)),
                ('suaresposta2', models.TextField(blank=True, default='', max_length=1000)),
                ('suaresposta3', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
