# Generated by Django 3.2.4 on 2021-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0008_dictclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictclass',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictclass',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
